### ISSUE TITLE
IP6.data fragments use type dpkt.udp.UDP when it should be bytes

### ISSUE THREAD

**Issue by mwander** [kbandla/dpkt#575]
Transport data of IPv4 fragments is set to type(dpkt.udp.UDP) only on the fragment with offset=0. Any other fragment uses type(bytes). I'd expect that IPv6 fragments are handled similarly.

However, data of IPv6 fragments use type(dpkt.udp.UDP) on all UDP fragments, irregardless of offset. This allows to retrieve sport, dport, ulen, sum from fragments, but the data will be arbitrary garbage, except for the first fragment with frag_off=0.

Suggestion: harmonize behavior of IP/IP6 and use type(bytes) for IPv6 data fragments with frag_off > 0.

Attached .py and .pcap reproduce the issue:
[dpkt-fragment-issue.zip](https://github.com/kbandla/dpkt/files/6566780/dpkt-fragment-issue.zip)

**Comment by obormot** [comment]
Thanks for the detailed bug report!  Looking into it

**Comment by obormot** [comment]
Addressed in PR https://github.com/kbandla/dpkt/pull/576

**Comment by mwander** [comment]
Thanks for the quick fix.
There is a regression issue in `IP6.__bytes__()` when writing packets. Stacktrace:

```
  File "anonymizepcap.py", line 148, in main
    pcap_writer.writepkt(frame, ts)
  File "/cygdrive/c/Users/mw/Documents/svn/msmt/anonymizepcap/dpkt/pcap.py", line 229, in writepkt
    self.writepkt_time(bytes(pkt), ts)
  File "/cygdrive/c/Users/mw/Documents/svn/msmt/anonymizepcap/dpkt/ethernet.py", line 268, in __bytes__
    return bytes(dpkt.Packet.__bytes__(self) + tail)
  File "/cygdrive/c/Users/mw/Documents/svn/msmt/anonymizepcap/dpkt/dpkt.py", line 149, in __bytes__
    return self.pack_hdr() + bytes(self.data)
  File "/cygdrive/c/Users/mw/Documents/svn/msmt/anonymizepcap/dpkt/ip6.py", line 125, in __bytes__
    if (self.p == 6 or self.p == 17 or self.p == 58) and not self.data.sum:
AttributeError: 'bytes' object has no attribute 'sum'
```

Suggestion for patch follows:
[issue575_regression.txt](https://github.com/kbandla/dpkt/files/6572024/issue575_regression.txt)

**Comment by obormot** [comment]
Regression addressed in PR https://github.com/kbandla/dpkt/pull/577

**Comment by obormot** [comment]
@mwander is the latest build working good for you?

**Comment by mwander** [comment]
Yes, can confirm. Thanks a lot!
