### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by kbandla** [kbandla/dpkt#152]
_From [f4b10r3...@gmail.com](https://code.google.com/u/100967907678196336186/) on July 04, 2014 09:10:08_

on windows 7 64, python 2.7
I try installing 1.7 or 1.8 via python setup.py install
and get

Traceback (most recent call last):
  File "setup.py", line 4, in \<module>
    import dpkt
  File "c:\Users\fabio\Downloads\dpkt-1.7\dpkt\__init__.py", line 24, in \<module>
    import ethernet
  File "c:\Users\fabio\Downloads\dpkt-1.7\dpkt\ethernet.py", line 128, in \<module>
    __load_types()
  File "c:\Users\fabio\Downloads\dpkt-1.7\dpkt\ethernet.py", line 122, in __load_types
    mod = __import__(modname, g)
  File "c:\Users\fabio\Downloads\dpkt-1.7\dpkt\ip6.py", line 95, in \<module>
    import ip
  File "c:\Users\fabio\Downloads\dpkt-1.7\dpkt\ip.py", line 255, in \<module>
    __load_protos()
  File "c:\Users\fabio\Downloads\dpkt-1.7\dpkt\ip.py", line 249, in __load_protos
    mod = __import__(name, g)
  File "C:\Python27\lib\site-packages\visa.py", line 1, in \<module>
    from pyvisa.visa import *
  File "C:\Python27\lib\site-packages\pyvisa\visa.py", line 231, in \<module>
    resource_manager = ResourceManager()
  File "C:\Python27\lib\site-packages\pyvisa\vpp43.py", line 105, in __new__
    it.init(*args, **kwds)
  File "C:\Python27\lib\site-packages\pyvisa\visa.py", line 227, in init
    self.session = self.vi = vpp43.open_default_resource_manager()
  File "C:\Python27\lib\site-packages\pyvisa\vpp43.py", line 758, in open_default_resource_manager
    visa_library().viOpenDefaultRM(byref(session))
  File "C:\Python27\lib\site-packages\pyvisa\vpp43.py", line 175, in __call__
    self.load_library()
  File "C:\Python27\lib\site-packages\pyvisa\vpp43.py", line 141, in load_library
    self.__lib       = windll.visa32
  File "C:\Python27\lib\ctypes\__init__.py", line 435, in __getattr__
    dll = self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

_Original issue: http://code.google.com/p/dpkt/issues/detail?id=126_

**Comment by kbandla** [comment]
_From [f4b10r3...@gmail.com](https://code.google.com/u/100967907678196336186/) on July 04, 2014 07:42:20_

after upgrading pyvisa from 1.4 to 1.5 

Traceback (most recent call last):
  File "setup.py", line 4, in \<module>
    import dpkt
  File "c:\Users\fabio\Downloads\dpkt-1.8\dpkt\__init__.py", line 24, in \<module>
    import ethernet
  File "c:\Users\fabio\Downloads\dpkt-1.8\dpkt\ethernet.py", line 128, in \<module>
    __load_types()
  File "c:\Users\fabio\Downloads\dpkt-1.8\dpkt\ethernet.py", line 122, in __load_types
    mod = __import__(modname, g)
  File "c:\Users\fabio\Downloads\dpkt-1.8\dpkt\ip6.py", line 101, in \<module>
    import ip
  File "c:\Users\fabio\Downloads\dpkt-1.8\dpkt\ip.py", line 258, in \<module>
    __load_protos()
  File "c:\Users\fabio\Downloads\dpkt-1.8\dpkt\ip.py", line 255, in __load_protos
    IP.set_proto(v, getattr(mod, name.upper()))
AttributeError: 'module' object has no attribute 'VISA'

**Comment by kbandla** [comment]
_From [lan4...@gmail.com](https://code.google.com/u/113851699615790030140/) on December 31, 2014 13:45:19_

I see the same issue on Linux even with the latest PyVISA 1.6.

**Comment by kbandla** [comment]
_From [lan4...@gmail.com](https://code.google.com/u/113851699615790030140/) on December 31, 2014 14:10:10_

With the patches on " Issue 34 :	dynamic module loading too careless", the problem fixed.

**Comment by brifordwylie** [comment]
Sounds like this one is ready to close
